- attrs: 
    calibration_date: 2024-08-15
    comment: beta470nm, beta532nm, beta650nm. This instrument is externally mounted, no data flow through glider.
    description: A variant of the ECO Puck Triplet (http://vocab.nerc.ac.uk/collection/L22/current/TOOL0673/). It is a three-optical-sensor, user-defined instrument that carries 3 scattering meters. ECO Pucks are real‚Äêtime only sensors as they are integrated onto the OEM platform that provides power and data handling. The SLO designation signifies this is a 1st generation model that is specific for integration into Slocum gliders. The fluorometers and scattering meter are single wavelength sensors. The model is depth-rated to 600 m.
    factory_calibrated: 2024-08-15
    long_name: WET Labs ECO BB3SLO
    maker: Sea-Bird Scientific,WET Labs
    maker_vocabulary: https://vocab.nerc.ac.uk/collection/B75/current/ORG00226/,https://vocab.nerc.ac.uk/collection/L35/current/MAN0026/
    model: WET Labs {Sea-Bird WETLabs} ECO Triplet BB3SLO scattering sensor
    model_vocabulary: https://vocab.nerc.ac.uk/collection/L22/current/TOOL1911/
    owner: University of the Virgin Islands
    references: ''
    serial_number: '9030'
    type: optical backscatter sensor
    type_vocabulary: http://vocab.nerc.ac.uk/collection/L05/current/123/
    user_calibrated: ''
  nc_var_name: instrument_bb3slo
  type: i4
